version: "4.27.1"

services:
  backend:
    container_name: taste-maker
    build:
      context: ./backend_api
      dockerfile: Dockerfile
    env_file:
      - ./backend_api/.env
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - static:/usr/src/TasteMaker/backend_api/static
      - media:/usr/src/TasteMaker/backend_api/media
    restart: always
    expose:
      - 8000
    ports:
      - "8000:8000"

volumes:
  media:
  static: