# Generated by Django 5.0.1 on 2024-01-29 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_cooking_time_and_more'),
        ('users', '0002_alter_user_login_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='users.user'),
            preserve_default=False,
        ),
    ]
